<?php

namespace App\TwoEighteen;

use App\DayClass;

class Eleventh extends DayClass
{
    private $input = 9005;

    public function primary()
    {
        return 0;
    }

    public function secondary()
    {
        parent::secondary(); // TODO: Change the autogenerated stub
    }
}