<?php

namespace App\TwoEighteen;

use App\DayClass;
use App\TwoEighteen\Classes\WarriorBeast;

class Fifteenth extends DayClass
{
//    protected $filepath = '2018/day_15.txt';
    protected $filepath = '2018/day_15.example_01.txt';
//    protected $filepath = '2018/day_15.example_02.txt';
//    protected $filepath = '2018/day_15.example_03.txt';
//    protected $filepath = '2018/day_15.example_04.txt';
//    protected $filepath = '2018/day_15.example_05.txt';
//    protected $filepath = '2018/day_15.example_06.txt';

    private $beasts;

    private $map = [];

    public function primary()
    {
        $this->createMap();
        $this->printMap();
    }

    public function secondary()
    {
        parent::secondary(); // TODO: Change the autogenerated stub
    }

    private function printMap($showDetail = false)
    {
        $mapStates = ['#', '.', 'G', 'E'];
        for($y = 0; $y < count($this->map); $y++){
            for($x = 0; $x < count($this->map[$y]); $x++){
                print $mapStates[$this->map[$y][$x]];
            }
            print chr(10);
        }
    }

    private function createMap()
    {
        $this->beasts = collect();
        $lines = $this->getInput();
        for($y = 0; $y < count($lines); $y++){
            $this->map[$y] = [];
            $l = trim($lines[$y]);
            for($x = 0; $x < strlen($l); $x++){
                /**
                 * 0: Wall
                 * 1: Free
                 * 2: Gnome
                 * 3: Elf
                 */
                if($l[$x] == '#'){
                    $this->map[$y][$x] = 0;
                }else{
                    if($l[$x] == 'G' || $l[$x] == 'E'){
                        $this->beasts->push(
                            new WarriorBeast($l[$x] == 'E', $x, $y)
                        );
                        $this->map[$y][$x] = $l[$x] == 'E' ?  3: 2;
                    }else{
                        $this->map[$y][$x] = 1;
                    }
                }


            }
        }

    }

}